name: Connect to an AWS role from a GitHub repository

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION : "eu-central-1"

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: clone the repository
        uses: actions/checkout@v3
      
      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.1

      - name: set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: build the app
        run: |
          corepack enable pnpm
          pnpm install --prod=false
          pnpm run build

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::851725582763:role/rat-dev-cicd-role
          aws-region: ${{ env.AWS_REGION }}

      - name: set up Terraform CLI for CI server
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.3"

      - name: deploy the app
        working-directory: infra
        run: |
          echo '${{ secrets.TF_BACKEND_CONFIG }}' > backend.tfvars
          terraform init -backend-config=backend.tfvars -reconfigure
          terraform workspace select dev
          echo '${{ secrets.TF_INPUT_VARIABLES }}' > input.tfvars
          terraform apply --auto-approve -var-file="input.tfvars"
